# Generated by Django 3.2.9 on 2021-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20211214_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_words_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
