# Generated by Django 3.2.9 on 2021-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Ivanov Ivan', max_length=255),
        ),
    ]
